package com.bruincreates.server.dao.po;

import java.util.Date;

public class Login {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.id
     *
     * @mbg.generated Sat Jan 08 14:40:25 PST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.username
     *
     * @mbg.generated Sat Jan 08 14:40:25 PST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.last_login_ip
     *
     * @mbg.generated Sat Jan 08 14:40:25 PST 2022
     */
    private String lastLoginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.last_login_time
     *
     * @mbg.generated Sat Jan 08 14:40:25 PST 2022
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.last_logout_time
     *
     * @mbg.generated Sat Jan 08 14:40:25 PST 2022
     */
    private Date lastLogoutTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.failed_login_attempts
     *
     * @mbg.generated Sat Jan 08 14:40:25 PST 2022
     */
    private Integer failedLoginAttempts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.id
     *
     * @return the value of login.id
     *
     * @mbg.generated Sat Jan 08 14:40:25 PST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.id
     *
     * @param id the value for login.id
     *
     * @mbg.generated Sat Jan 08 14:40:25 PST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.username
     *
     * @return the value of login.username
     *
     * @mbg.generated Sat Jan 08 14:40:25 PST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.username
     *
     * @param username the value for login.username
     *
     * @mbg.generated Sat Jan 08 14:40:25 PST 2022
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.last_login_ip
     *
     * @return the value of login.last_login_ip
     *
     * @mbg.generated Sat Jan 08 14:40:25 PST 2022
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.last_login_ip
     *
     * @param lastLoginIp the value for login.last_login_ip
     *
     * @mbg.generated Sat Jan 08 14:40:25 PST 2022
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.last_login_time
     *
     * @return the value of login.last_login_time
     *
     * @mbg.generated Sat Jan 08 14:40:25 PST 2022
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.last_login_time
     *
     * @param lastLoginTime the value for login.last_login_time
     *
     * @mbg.generated Sat Jan 08 14:40:25 PST 2022
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.last_logout_time
     *
     * @return the value of login.last_logout_time
     *
     * @mbg.generated Sat Jan 08 14:40:25 PST 2022
     */
    public Date getLastLogoutTime() {
        return lastLogoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.last_logout_time
     *
     * @param lastLogoutTime the value for login.last_logout_time
     *
     * @mbg.generated Sat Jan 08 14:40:25 PST 2022
     */
    public void setLastLogoutTime(Date lastLogoutTime) {
        this.lastLogoutTime = lastLogoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.failed_login_attempts
     *
     * @return the value of login.failed_login_attempts
     *
     * @mbg.generated Sat Jan 08 14:40:25 PST 2022
     */
    public Integer getFailedLoginAttempts() {
        return failedLoginAttempts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.failed_login_attempts
     *
     * @param failedLoginAttempts the value for login.failed_login_attempts
     *
     * @mbg.generated Sat Jan 08 14:40:25 PST 2022
     */
    public void setFailedLoginAttempts(Integer failedLoginAttempts) {
        this.failedLoginAttempts = failedLoginAttempts;
    }
}