package com.bruincreates.server.dao.po;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_id
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.product_id
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.buyer_id
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    private String buyerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.seller_id
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    private String sellerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_type
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    private Byte orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_status
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    private Byte orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.shipping_charge
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    private BigDecimal shippingCharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.total_charge
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    private BigDecimal totalCharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.date_created
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    private Date dateCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.deleted
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_id
     *
     * @return the value of order.order_id
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_id
     *
     * @param orderId the value for order.order_id
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.product_id
     *
     * @return the value of order.product_id
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.product_id
     *
     * @param productId the value for order.product_id
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.buyer_id
     *
     * @return the value of order.buyer_id
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    public String getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.buyer_id
     *
     * @param buyerId the value for order.buyer_id
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    public void setBuyerId(String buyerId) {
        this.buyerId = buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.seller_id
     *
     * @return the value of order.seller_id
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.seller_id
     *
     * @param sellerId the value for order.seller_id
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_type
     *
     * @return the value of order.order_type
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    public Byte getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_type
     *
     * @param orderType the value for order.order_type
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    public void setOrderType(Byte orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_status
     *
     * @return the value of order.order_status
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    public Byte getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_status
     *
     * @param orderStatus the value for order.order_status
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    public void setOrderStatus(Byte orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.shipping_charge
     *
     * @return the value of order.shipping_charge
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    public BigDecimal getShippingCharge() {
        return shippingCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.shipping_charge
     *
     * @param shippingCharge the value for order.shipping_charge
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    public void setShippingCharge(BigDecimal shippingCharge) {
        this.shippingCharge = shippingCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.total_charge
     *
     * @return the value of order.total_charge
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    public BigDecimal getTotalCharge() {
        return totalCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.total_charge
     *
     * @param totalCharge the value for order.total_charge
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    public void setTotalCharge(BigDecimal totalCharge) {
        this.totalCharge = totalCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.date_created
     *
     * @return the value of order.date_created
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.date_created
     *
     * @param dateCreated the value for order.date_created
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.deleted
     *
     * @return the value of order.deleted
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.deleted
     *
     * @param deleted the value for order.deleted
     *
     * @mbg.generated Sat Jan 29 21:37:18 PST 2022
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}