package com.bruincreates.server.dao.po;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated Sat Jan 29 18:49:55 PST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_id
     *
     * @mbg.generated Sat Jan 29 18:49:55 PST 2022
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.buyer
     *
     * @mbg.generated Sat Jan 29 18:49:55 PST 2022
     */
    private String buyer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.seller
     *
     * @mbg.generated Sat Jan 29 18:49:55 PST 2022
     */
    private String seller;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.type
     *
     * @mbg.generated Sat Jan 29 18:49:55 PST 2022
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.status
     *
     * @mbg.generated Sat Jan 29 18:49:55 PST 2022
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.shipping
     *
     * @mbg.generated Sat Jan 29 18:49:55 PST 2022
     */
    private BigDecimal shipping;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.total
     *
     * @mbg.generated Sat Jan 29 18:49:55 PST 2022
     */
    private BigDecimal total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.create_time
     *
     * @mbg.generated Sat Jan 29 18:49:55 PST 2022
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated Sat Jan 29 18:49:55 PST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated Sat Jan 29 18:49:55 PST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_id
     *
     * @return the value of order.order_id
     *
     * @mbg.generated Sat Jan 29 18:49:55 PST 2022
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_id
     *
     * @param orderId the value for order.order_id
     *
     * @mbg.generated Sat Jan 29 18:49:55 PST 2022
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.buyer
     *
     * @return the value of order.buyer
     *
     * @mbg.generated Sat Jan 29 18:49:55 PST 2022
     */
    public String getBuyer() {
        return buyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.buyer
     *
     * @param buyer the value for order.buyer
     *
     * @mbg.generated Sat Jan 29 18:49:55 PST 2022
     */
    public void setBuyer(String buyer) {
        this.buyer = buyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.seller
     *
     * @return the value of order.seller
     *
     * @mbg.generated Sat Jan 29 18:49:55 PST 2022
     */
    public String getSeller() {
        return seller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.seller
     *
     * @param seller the value for order.seller
     *
     * @mbg.generated Sat Jan 29 18:49:55 PST 2022
     */
    public void setSeller(String seller) {
        this.seller = seller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.type
     *
     * @return the value of order.type
     *
     * @mbg.generated Sat Jan 29 18:49:55 PST 2022
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.type
     *
     * @param type the value for order.type
     *
     * @mbg.generated Sat Jan 29 18:49:55 PST 2022
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.status
     *
     * @return the value of order.status
     *
     * @mbg.generated Sat Jan 29 18:49:55 PST 2022
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.status
     *
     * @param status the value for order.status
     *
     * @mbg.generated Sat Jan 29 18:49:55 PST 2022
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.shipping
     *
     * @return the value of order.shipping
     *
     * @mbg.generated Sat Jan 29 18:49:55 PST 2022
     */
    public BigDecimal getShipping() {
        return shipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.shipping
     *
     * @param shipping the value for order.shipping
     *
     * @mbg.generated Sat Jan 29 18:49:55 PST 2022
     */
    public void setShipping(BigDecimal shipping) {
        this.shipping = shipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.total
     *
     * @return the value of order.total
     *
     * @mbg.generated Sat Jan 29 18:49:55 PST 2022
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.total
     *
     * @param total the value for order.total
     *
     * @mbg.generated Sat Jan 29 18:49:55 PST 2022
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.create_time
     *
     * @return the value of order.create_time
     *
     * @mbg.generated Sat Jan 29 18:49:55 PST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.create_time
     *
     * @param createTime the value for order.create_time
     *
     * @mbg.generated Sat Jan 29 18:49:55 PST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}