package com.bruincreates.server.dao.po;

public class ProductCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.id
     *
     * @mbg.generated Tue Jan 11 15:34:50 PST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.category
     *
     * @mbg.generated Tue Jan 11 15:34:50 PST 2022
     */
    private String category;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.id
     *
     * @return the value of product_category.id
     *
     * @mbg.generated Tue Jan 11 15:34:50 PST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.id
     *
     * @param id the value for product_category.id
     *
     * @mbg.generated Tue Jan 11 15:34:50 PST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.category
     *
     * @return the value of product_category.category
     *
     * @mbg.generated Tue Jan 11 15:34:50 PST 2022
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.category
     *
     * @param category the value for product_category.category
     *
     * @mbg.generated Tue Jan 11 15:34:50 PST 2022
     */
    public void setCategory(String category) {
        this.category = category;
    }
}