package com.bruincreates.server.dao.po;

public class ProductReview {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_review.id
     *
     * @mbg.generated Tue Jan 11 15:35:05 PST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_review.username
     *
     * @mbg.generated Tue Jan 11 15:35:05 PST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_review.product_id
     *
     * @mbg.generated Tue Jan 11 15:35:05 PST 2022
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_review.review
     *
     * @mbg.generated Tue Jan 11 15:35:05 PST 2022
     */
    private String review;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_review.id
     *
     * @return the value of product_review.id
     *
     * @mbg.generated Tue Jan 11 15:35:05 PST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_review.id
     *
     * @param id the value for product_review.id
     *
     * @mbg.generated Tue Jan 11 15:35:05 PST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_review.username
     *
     * @return the value of product_review.username
     *
     * @mbg.generated Tue Jan 11 15:35:05 PST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_review.username
     *
     * @param username the value for product_review.username
     *
     * @mbg.generated Tue Jan 11 15:35:05 PST 2022
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_review.product_id
     *
     * @return the value of product_review.product_id
     *
     * @mbg.generated Tue Jan 11 15:35:05 PST 2022
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_review.product_id
     *
     * @param productId the value for product_review.product_id
     *
     * @mbg.generated Tue Jan 11 15:35:05 PST 2022
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_review.review
     *
     * @return the value of product_review.review
     *
     * @mbg.generated Tue Jan 11 15:35:05 PST 2022
     */
    public String getReview() {
        return review;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_review.review
     *
     * @param review the value for product_review.review
     *
     * @mbg.generated Tue Jan 11 15:35:05 PST 2022
     */
    public void setReview(String review) {
        this.review = review;
    }
}