package com.bruincreates.server.dao.po;

import java.util.Date;

public class ProductReview {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_review.id
     *
     * @mbg.generated Sat Jan 29 19:32:16 PST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_review.buyer_id
     *
     * @mbg.generated Sat Jan 29 19:32:16 PST 2022
     */
    private String buyerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_review.product_id
     *
     * @mbg.generated Sat Jan 29 19:32:16 PST 2022
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_review.product_review
     *
     * @mbg.generated Sat Jan 29 19:32:16 PST 2022
     */
    private String productReview;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_review.date_created
     *
     * @mbg.generated Sat Jan 29 19:32:16 PST 2022
     */
    private Date dateCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_review.deleted
     *
     * @mbg.generated Sat Jan 29 19:32:16 PST 2022
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_review.id
     *
     * @return the value of product_review.id
     *
     * @mbg.generated Sat Jan 29 19:32:16 PST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_review.id
     *
     * @param id the value for product_review.id
     *
     * @mbg.generated Sat Jan 29 19:32:16 PST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_review.buyer_id
     *
     * @return the value of product_review.buyer_id
     *
     * @mbg.generated Sat Jan 29 19:32:16 PST 2022
     */
    public String getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_review.buyer_id
     *
     * @param buyerId the value for product_review.buyer_id
     *
     * @mbg.generated Sat Jan 29 19:32:16 PST 2022
     */
    public void setBuyerId(String buyerId) {
        this.buyerId = buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_review.product_id
     *
     * @return the value of product_review.product_id
     *
     * @mbg.generated Sat Jan 29 19:32:16 PST 2022
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_review.product_id
     *
     * @param productId the value for product_review.product_id
     *
     * @mbg.generated Sat Jan 29 19:32:16 PST 2022
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_review.product_review
     *
     * @return the value of product_review.product_review
     *
     * @mbg.generated Sat Jan 29 19:32:16 PST 2022
     */
    public String getProductReview() {
        return productReview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_review.product_review
     *
     * @param productReview the value for product_review.product_review
     *
     * @mbg.generated Sat Jan 29 19:32:16 PST 2022
     */
    public void setProductReview(String productReview) {
        this.productReview = productReview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_review.date_created
     *
     * @return the value of product_review.date_created
     *
     * @mbg.generated Sat Jan 29 19:32:16 PST 2022
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_review.date_created
     *
     * @param dateCreated the value for product_review.date_created
     *
     * @mbg.generated Sat Jan 29 19:32:16 PST 2022
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_review.deleted
     *
     * @return the value of product_review.deleted
     *
     * @mbg.generated Sat Jan 29 19:32:16 PST 2022
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_review.deleted
     *
     * @param deleted the value for product_review.deleted
     *
     * @mbg.generated Sat Jan 29 19:32:16 PST 2022
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}