package com.bruincreates.server.dao.po;

import java.math.BigDecimal;
import java.util.Date;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_id
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.seller_id
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    private String sellerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_type
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    private Byte productType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_title
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    private String productTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_category
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    private String productCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.keywords
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_description
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    private String productDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_images
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    private String productImages;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_stock
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    private Integer productStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_price
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    private BigDecimal productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.date_created
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    private Date dateCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.deleted
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_id
     *
     * @return the value of product.product_id
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_id
     *
     * @param productId the value for product.product_id
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.seller_id
     *
     * @return the value of product.seller_id
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.seller_id
     *
     * @param sellerId the value for product.seller_id
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_type
     *
     * @return the value of product.product_type
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    public Byte getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_type
     *
     * @param productType the value for product.product_type
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    public void setProductType(Byte productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_title
     *
     * @return the value of product.product_title
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    public String getProductTitle() {
        return productTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_title
     *
     * @param productTitle the value for product.product_title
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    public void setProductTitle(String productTitle) {
        this.productTitle = productTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_category
     *
     * @return the value of product.product_category
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    public String getProductCategory() {
        return productCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_category
     *
     * @param productCategory the value for product.product_category
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    public void setProductCategory(String productCategory) {
        this.productCategory = productCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.keywords
     *
     * @return the value of product.keywords
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.keywords
     *
     * @param keywords the value for product.keywords
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_description
     *
     * @return the value of product.product_description
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    public String getProductDescription() {
        return productDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_description
     *
     * @param productDescription the value for product.product_description
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_images
     *
     * @return the value of product.product_images
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    public String getProductImages() {
        return productImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_images
     *
     * @param productImages the value for product.product_images
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    public void setProductImages(String productImages) {
        this.productImages = productImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_stock
     *
     * @return the value of product.product_stock
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    public Integer getProductStock() {
        return productStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_stock
     *
     * @param productStock the value for product.product_stock
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    public void setProductStock(Integer productStock) {
        this.productStock = productStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_price
     *
     * @return the value of product.product_price
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_price
     *
     * @param productPrice the value for product.product_price
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.date_created
     *
     * @return the value of product.date_created
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.date_created
     *
     * @param dateCreated the value for product.date_created
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.deleted
     *
     * @return the value of product.deleted
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.deleted
     *
     * @param deleted the value for product.deleted
     *
     * @mbg.generated Sat Jan 29 19:31:53 PST 2022
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}