package com.bruincreates.server.dao.po;

public class UserAuth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.id
     *
     * @mbg.generated Fri Jan 07 09:51:44 PST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.username
     *
     * @mbg.generated Fri Jan 07 09:51:44 PST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.auth_provider
     *
     * @mbg.generated Fri Jan 07 09:51:44 PST 2022
     */
    private String authProvider;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.auth_uid
     *
     * @mbg.generated Fri Jan 07 09:51:44 PST 2022
     */
    private String authUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.auth_token
     *
     * @mbg.generated Fri Jan 07 09:51:44 PST 2022
     */
    private String authToken;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.id
     *
     * @return the value of user_auth.id
     *
     * @mbg.generated Fri Jan 07 09:51:44 PST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.id
     *
     * @param id the value for user_auth.id
     *
     * @mbg.generated Fri Jan 07 09:51:44 PST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.username
     *
     * @return the value of user_auth.username
     *
     * @mbg.generated Fri Jan 07 09:51:44 PST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.username
     *
     * @param username the value for user_auth.username
     *
     * @mbg.generated Fri Jan 07 09:51:44 PST 2022
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.auth_provider
     *
     * @return the value of user_auth.auth_provider
     *
     * @mbg.generated Fri Jan 07 09:51:44 PST 2022
     */
    public String getAuthProvider() {
        return authProvider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.auth_provider
     *
     * @param authProvider the value for user_auth.auth_provider
     *
     * @mbg.generated Fri Jan 07 09:51:44 PST 2022
     */
    public void setAuthProvider(String authProvider) {
        this.authProvider = authProvider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.auth_uid
     *
     * @return the value of user_auth.auth_uid
     *
     * @mbg.generated Fri Jan 07 09:51:44 PST 2022
     */
    public String getAuthUid() {
        return authUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.auth_uid
     *
     * @param authUid the value for user_auth.auth_uid
     *
     * @mbg.generated Fri Jan 07 09:51:44 PST 2022
     */
    public void setAuthUid(String authUid) {
        this.authUid = authUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.auth_token
     *
     * @return the value of user_auth.auth_token
     *
     * @mbg.generated Fri Jan 07 09:51:44 PST 2022
     */
    public String getAuthToken() {
        return authToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.auth_token
     *
     * @param authToken the value for user_auth.auth_token
     *
     * @mbg.generated Fri Jan 07 09:51:44 PST 2022
     */
    public void setAuthToken(String authToken) {
        this.authToken = authToken;
    }
}