package com.bruincreates.server.dao.po;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobile
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    private Integer mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.profile_name
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    private String profileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.avatar_url
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.bio
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    private String bio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.data_created
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    private Date dataCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.role
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    private Integer role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email_verified
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    private Integer emailVerified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.account_locked
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    private Integer accountLocked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.account_disabled
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    private Integer accountDisabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.account_deleted
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    private Integer accountDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobile
     *
     * @return the value of user.mobile
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public Integer getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobile
     *
     * @param mobile the value for user.mobile
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public void setMobile(Integer mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.profile_name
     *
     * @return the value of user.profile_name
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public String getProfileName() {
        return profileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.profile_name
     *
     * @param profileName the value for user.profile_name
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public void setProfileName(String profileName) {
        this.profileName = profileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.avatar_url
     *
     * @return the value of user.avatar_url
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.avatar_url
     *
     * @param avatarUrl the value for user.avatar_url
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.bio
     *
     * @return the value of user.bio
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public String getBio() {
        return bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.bio
     *
     * @param bio the value for user.bio
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public void setBio(String bio) {
        this.bio = bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.data_created
     *
     * @return the value of user.data_created
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public Date getDataCreated() {
        return dataCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.data_created
     *
     * @param dataCreated the value for user.data_created
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public void setDataCreated(Date dataCreated) {
        this.dataCreated = dataCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.role
     *
     * @return the value of user.role
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.role
     *
     * @param role the value for user.role
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email_verified
     *
     * @return the value of user.email_verified
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public Integer getEmailVerified() {
        return emailVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email_verified
     *
     * @param emailVerified the value for user.email_verified
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public void setEmailVerified(Integer emailVerified) {
        this.emailVerified = emailVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.account_locked
     *
     * @return the value of user.account_locked
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public Integer getAccountLocked() {
        return accountLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.account_locked
     *
     * @param accountLocked the value for user.account_locked
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public void setAccountLocked(Integer accountLocked) {
        this.accountLocked = accountLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.account_disabled
     *
     * @return the value of user.account_disabled
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public Integer getAccountDisabled() {
        return accountDisabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.account_disabled
     *
     * @param accountDisabled the value for user.account_disabled
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public void setAccountDisabled(Integer accountDisabled) {
        this.accountDisabled = accountDisabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.account_deleted
     *
     * @return the value of user.account_deleted
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public Integer getAccountDeleted() {
        return accountDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.account_deleted
     *
     * @param accountDeleted the value for user.account_deleted
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public void setAccountDeleted(Integer accountDeleted) {
        this.accountDeleted = accountDeleted;
    }
}