package com.bruincreates.server.dao.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(Integer value) {
            addCriterion("mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(Integer value) {
            addCriterion("mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(Integer value) {
            addCriterion("mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(Integer value) {
            addCriterion("mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(Integer value) {
            addCriterion("mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(Integer value) {
            addCriterion("mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<Integer> values) {
            addCriterion("mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<Integer> values) {
            addCriterion("mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(Integer value1, Integer value2) {
            addCriterion("mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(Integer value1, Integer value2) {
            addCriterion("mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andProfileNameIsNull() {
            addCriterion("profile_name is null");
            return (Criteria) this;
        }

        public Criteria andProfileNameIsNotNull() {
            addCriterion("profile_name is not null");
            return (Criteria) this;
        }

        public Criteria andProfileNameEqualTo(String value) {
            addCriterion("profile_name =", value, "profileName");
            return (Criteria) this;
        }

        public Criteria andProfileNameNotEqualTo(String value) {
            addCriterion("profile_name <>", value, "profileName");
            return (Criteria) this;
        }

        public Criteria andProfileNameGreaterThan(String value) {
            addCriterion("profile_name >", value, "profileName");
            return (Criteria) this;
        }

        public Criteria andProfileNameGreaterThanOrEqualTo(String value) {
            addCriterion("profile_name >=", value, "profileName");
            return (Criteria) this;
        }

        public Criteria andProfileNameLessThan(String value) {
            addCriterion("profile_name <", value, "profileName");
            return (Criteria) this;
        }

        public Criteria andProfileNameLessThanOrEqualTo(String value) {
            addCriterion("profile_name <=", value, "profileName");
            return (Criteria) this;
        }

        public Criteria andProfileNameLike(String value) {
            addCriterion("profile_name like", value, "profileName");
            return (Criteria) this;
        }

        public Criteria andProfileNameNotLike(String value) {
            addCriterion("profile_name not like", value, "profileName");
            return (Criteria) this;
        }

        public Criteria andProfileNameIn(List<String> values) {
            addCriterion("profile_name in", values, "profileName");
            return (Criteria) this;
        }

        public Criteria andProfileNameNotIn(List<String> values) {
            addCriterion("profile_name not in", values, "profileName");
            return (Criteria) this;
        }

        public Criteria andProfileNameBetween(String value1, String value2) {
            addCriterion("profile_name between", value1, value2, "profileName");
            return (Criteria) this;
        }

        public Criteria andProfileNameNotBetween(String value1, String value2) {
            addCriterion("profile_name not between", value1, value2, "profileName");
            return (Criteria) this;
        }

        public Criteria andAvatarUrlIsNull() {
            addCriterion("avatar_url is null");
            return (Criteria) this;
        }

        public Criteria andAvatarUrlIsNotNull() {
            addCriterion("avatar_url is not null");
            return (Criteria) this;
        }

        public Criteria andAvatarUrlEqualTo(String value) {
            addCriterion("avatar_url =", value, "avatarUrl");
            return (Criteria) this;
        }

        public Criteria andAvatarUrlNotEqualTo(String value) {
            addCriterion("avatar_url <>", value, "avatarUrl");
            return (Criteria) this;
        }

        public Criteria andAvatarUrlGreaterThan(String value) {
            addCriterion("avatar_url >", value, "avatarUrl");
            return (Criteria) this;
        }

        public Criteria andAvatarUrlGreaterThanOrEqualTo(String value) {
            addCriterion("avatar_url >=", value, "avatarUrl");
            return (Criteria) this;
        }

        public Criteria andAvatarUrlLessThan(String value) {
            addCriterion("avatar_url <", value, "avatarUrl");
            return (Criteria) this;
        }

        public Criteria andAvatarUrlLessThanOrEqualTo(String value) {
            addCriterion("avatar_url <=", value, "avatarUrl");
            return (Criteria) this;
        }

        public Criteria andAvatarUrlLike(String value) {
            addCriterion("avatar_url like", value, "avatarUrl");
            return (Criteria) this;
        }

        public Criteria andAvatarUrlNotLike(String value) {
            addCriterion("avatar_url not like", value, "avatarUrl");
            return (Criteria) this;
        }

        public Criteria andAvatarUrlIn(List<String> values) {
            addCriterion("avatar_url in", values, "avatarUrl");
            return (Criteria) this;
        }

        public Criteria andAvatarUrlNotIn(List<String> values) {
            addCriterion("avatar_url not in", values, "avatarUrl");
            return (Criteria) this;
        }

        public Criteria andAvatarUrlBetween(String value1, String value2) {
            addCriterion("avatar_url between", value1, value2, "avatarUrl");
            return (Criteria) this;
        }

        public Criteria andAvatarUrlNotBetween(String value1, String value2) {
            addCriterion("avatar_url not between", value1, value2, "avatarUrl");
            return (Criteria) this;
        }

        public Criteria andBioIsNull() {
            addCriterion("bio is null");
            return (Criteria) this;
        }

        public Criteria andBioIsNotNull() {
            addCriterion("bio is not null");
            return (Criteria) this;
        }

        public Criteria andBioEqualTo(String value) {
            addCriterion("bio =", value, "bio");
            return (Criteria) this;
        }

        public Criteria andBioNotEqualTo(String value) {
            addCriterion("bio <>", value, "bio");
            return (Criteria) this;
        }

        public Criteria andBioGreaterThan(String value) {
            addCriterion("bio >", value, "bio");
            return (Criteria) this;
        }

        public Criteria andBioGreaterThanOrEqualTo(String value) {
            addCriterion("bio >=", value, "bio");
            return (Criteria) this;
        }

        public Criteria andBioLessThan(String value) {
            addCriterion("bio <", value, "bio");
            return (Criteria) this;
        }

        public Criteria andBioLessThanOrEqualTo(String value) {
            addCriterion("bio <=", value, "bio");
            return (Criteria) this;
        }

        public Criteria andBioLike(String value) {
            addCriterion("bio like", value, "bio");
            return (Criteria) this;
        }

        public Criteria andBioNotLike(String value) {
            addCriterion("bio not like", value, "bio");
            return (Criteria) this;
        }

        public Criteria andBioIn(List<String> values) {
            addCriterion("bio in", values, "bio");
            return (Criteria) this;
        }

        public Criteria andBioNotIn(List<String> values) {
            addCriterion("bio not in", values, "bio");
            return (Criteria) this;
        }

        public Criteria andBioBetween(String value1, String value2) {
            addCriterion("bio between", value1, value2, "bio");
            return (Criteria) this;
        }

        public Criteria andBioNotBetween(String value1, String value2) {
            addCriterion("bio not between", value1, value2, "bio");
            return (Criteria) this;
        }

        public Criteria andDataCreatedIsNull() {
            addCriterion("data_created is null");
            return (Criteria) this;
        }

        public Criteria andDataCreatedIsNotNull() {
            addCriterion("data_created is not null");
            return (Criteria) this;
        }

        public Criteria andDataCreatedEqualTo(Date value) {
            addCriterion("data_created =", value, "dataCreated");
            return (Criteria) this;
        }

        public Criteria andDataCreatedNotEqualTo(Date value) {
            addCriterion("data_created <>", value, "dataCreated");
            return (Criteria) this;
        }

        public Criteria andDataCreatedGreaterThan(Date value) {
            addCriterion("data_created >", value, "dataCreated");
            return (Criteria) this;
        }

        public Criteria andDataCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("data_created >=", value, "dataCreated");
            return (Criteria) this;
        }

        public Criteria andDataCreatedLessThan(Date value) {
            addCriterion("data_created <", value, "dataCreated");
            return (Criteria) this;
        }

        public Criteria andDataCreatedLessThanOrEqualTo(Date value) {
            addCriterion("data_created <=", value, "dataCreated");
            return (Criteria) this;
        }

        public Criteria andDataCreatedIn(List<Date> values) {
            addCriterion("data_created in", values, "dataCreated");
            return (Criteria) this;
        }

        public Criteria andDataCreatedNotIn(List<Date> values) {
            addCriterion("data_created not in", values, "dataCreated");
            return (Criteria) this;
        }

        public Criteria andDataCreatedBetween(Date value1, Date value2) {
            addCriterion("data_created between", value1, value2, "dataCreated");
            return (Criteria) this;
        }

        public Criteria andDataCreatedNotBetween(Date value1, Date value2) {
            addCriterion("data_created not between", value1, value2, "dataCreated");
            return (Criteria) this;
        }

        public Criteria andRoleIsNull() {
            addCriterion("role is null");
            return (Criteria) this;
        }

        public Criteria andRoleIsNotNull() {
            addCriterion("role is not null");
            return (Criteria) this;
        }

        public Criteria andRoleEqualTo(Integer value) {
            addCriterion("role =", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotEqualTo(Integer value) {
            addCriterion("role <>", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleGreaterThan(Integer value) {
            addCriterion("role >", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleGreaterThanOrEqualTo(Integer value) {
            addCriterion("role >=", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleLessThan(Integer value) {
            addCriterion("role <", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleLessThanOrEqualTo(Integer value) {
            addCriterion("role <=", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleIn(List<Integer> values) {
            addCriterion("role in", values, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotIn(List<Integer> values) {
            addCriterion("role not in", values, "role");
            return (Criteria) this;
        }

        public Criteria andRoleBetween(Integer value1, Integer value2) {
            addCriterion("role between", value1, value2, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotBetween(Integer value1, Integer value2) {
            addCriterion("role not between", value1, value2, "role");
            return (Criteria) this;
        }

        public Criteria andEmailVerifiedIsNull() {
            addCriterion("email_verified is null");
            return (Criteria) this;
        }

        public Criteria andEmailVerifiedIsNotNull() {
            addCriterion("email_verified is not null");
            return (Criteria) this;
        }

        public Criteria andEmailVerifiedEqualTo(Integer value) {
            addCriterion("email_verified =", value, "emailVerified");
            return (Criteria) this;
        }

        public Criteria andEmailVerifiedNotEqualTo(Integer value) {
            addCriterion("email_verified <>", value, "emailVerified");
            return (Criteria) this;
        }

        public Criteria andEmailVerifiedGreaterThan(Integer value) {
            addCriterion("email_verified >", value, "emailVerified");
            return (Criteria) this;
        }

        public Criteria andEmailVerifiedGreaterThanOrEqualTo(Integer value) {
            addCriterion("email_verified >=", value, "emailVerified");
            return (Criteria) this;
        }

        public Criteria andEmailVerifiedLessThan(Integer value) {
            addCriterion("email_verified <", value, "emailVerified");
            return (Criteria) this;
        }

        public Criteria andEmailVerifiedLessThanOrEqualTo(Integer value) {
            addCriterion("email_verified <=", value, "emailVerified");
            return (Criteria) this;
        }

        public Criteria andEmailVerifiedIn(List<Integer> values) {
            addCriterion("email_verified in", values, "emailVerified");
            return (Criteria) this;
        }

        public Criteria andEmailVerifiedNotIn(List<Integer> values) {
            addCriterion("email_verified not in", values, "emailVerified");
            return (Criteria) this;
        }

        public Criteria andEmailVerifiedBetween(Integer value1, Integer value2) {
            addCriterion("email_verified between", value1, value2, "emailVerified");
            return (Criteria) this;
        }

        public Criteria andEmailVerifiedNotBetween(Integer value1, Integer value2) {
            addCriterion("email_verified not between", value1, value2, "emailVerified");
            return (Criteria) this;
        }

        public Criteria andAccountLockedIsNull() {
            addCriterion("account_locked is null");
            return (Criteria) this;
        }

        public Criteria andAccountLockedIsNotNull() {
            addCriterion("account_locked is not null");
            return (Criteria) this;
        }

        public Criteria andAccountLockedEqualTo(Integer value) {
            addCriterion("account_locked =", value, "accountLocked");
            return (Criteria) this;
        }

        public Criteria andAccountLockedNotEqualTo(Integer value) {
            addCriterion("account_locked <>", value, "accountLocked");
            return (Criteria) this;
        }

        public Criteria andAccountLockedGreaterThan(Integer value) {
            addCriterion("account_locked >", value, "accountLocked");
            return (Criteria) this;
        }

        public Criteria andAccountLockedGreaterThanOrEqualTo(Integer value) {
            addCriterion("account_locked >=", value, "accountLocked");
            return (Criteria) this;
        }

        public Criteria andAccountLockedLessThan(Integer value) {
            addCriterion("account_locked <", value, "accountLocked");
            return (Criteria) this;
        }

        public Criteria andAccountLockedLessThanOrEqualTo(Integer value) {
            addCriterion("account_locked <=", value, "accountLocked");
            return (Criteria) this;
        }

        public Criteria andAccountLockedIn(List<Integer> values) {
            addCriterion("account_locked in", values, "accountLocked");
            return (Criteria) this;
        }

        public Criteria andAccountLockedNotIn(List<Integer> values) {
            addCriterion("account_locked not in", values, "accountLocked");
            return (Criteria) this;
        }

        public Criteria andAccountLockedBetween(Integer value1, Integer value2) {
            addCriterion("account_locked between", value1, value2, "accountLocked");
            return (Criteria) this;
        }

        public Criteria andAccountLockedNotBetween(Integer value1, Integer value2) {
            addCriterion("account_locked not between", value1, value2, "accountLocked");
            return (Criteria) this;
        }

        public Criteria andAccountDisabledIsNull() {
            addCriterion("account_disabled is null");
            return (Criteria) this;
        }

        public Criteria andAccountDisabledIsNotNull() {
            addCriterion("account_disabled is not null");
            return (Criteria) this;
        }

        public Criteria andAccountDisabledEqualTo(Integer value) {
            addCriterion("account_disabled =", value, "accountDisabled");
            return (Criteria) this;
        }

        public Criteria andAccountDisabledNotEqualTo(Integer value) {
            addCriterion("account_disabled <>", value, "accountDisabled");
            return (Criteria) this;
        }

        public Criteria andAccountDisabledGreaterThan(Integer value) {
            addCriterion("account_disabled >", value, "accountDisabled");
            return (Criteria) this;
        }

        public Criteria andAccountDisabledGreaterThanOrEqualTo(Integer value) {
            addCriterion("account_disabled >=", value, "accountDisabled");
            return (Criteria) this;
        }

        public Criteria andAccountDisabledLessThan(Integer value) {
            addCriterion("account_disabled <", value, "accountDisabled");
            return (Criteria) this;
        }

        public Criteria andAccountDisabledLessThanOrEqualTo(Integer value) {
            addCriterion("account_disabled <=", value, "accountDisabled");
            return (Criteria) this;
        }

        public Criteria andAccountDisabledIn(List<Integer> values) {
            addCriterion("account_disabled in", values, "accountDisabled");
            return (Criteria) this;
        }

        public Criteria andAccountDisabledNotIn(List<Integer> values) {
            addCriterion("account_disabled not in", values, "accountDisabled");
            return (Criteria) this;
        }

        public Criteria andAccountDisabledBetween(Integer value1, Integer value2) {
            addCriterion("account_disabled between", value1, value2, "accountDisabled");
            return (Criteria) this;
        }

        public Criteria andAccountDisabledNotBetween(Integer value1, Integer value2) {
            addCriterion("account_disabled not between", value1, value2, "accountDisabled");
            return (Criteria) this;
        }

        public Criteria andAccountDeletedIsNull() {
            addCriterion("account_deleted is null");
            return (Criteria) this;
        }

        public Criteria andAccountDeletedIsNotNull() {
            addCriterion("account_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andAccountDeletedEqualTo(Integer value) {
            addCriterion("account_deleted =", value, "accountDeleted");
            return (Criteria) this;
        }

        public Criteria andAccountDeletedNotEqualTo(Integer value) {
            addCriterion("account_deleted <>", value, "accountDeleted");
            return (Criteria) this;
        }

        public Criteria andAccountDeletedGreaterThan(Integer value) {
            addCriterion("account_deleted >", value, "accountDeleted");
            return (Criteria) this;
        }

        public Criteria andAccountDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("account_deleted >=", value, "accountDeleted");
            return (Criteria) this;
        }

        public Criteria andAccountDeletedLessThan(Integer value) {
            addCriterion("account_deleted <", value, "accountDeleted");
            return (Criteria) this;
        }

        public Criteria andAccountDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("account_deleted <=", value, "accountDeleted");
            return (Criteria) this;
        }

        public Criteria andAccountDeletedIn(List<Integer> values) {
            addCriterion("account_deleted in", values, "accountDeleted");
            return (Criteria) this;
        }

        public Criteria andAccountDeletedNotIn(List<Integer> values) {
            addCriterion("account_deleted not in", values, "accountDeleted");
            return (Criteria) this;
        }

        public Criteria andAccountDeletedBetween(Integer value1, Integer value2) {
            addCriterion("account_deleted between", value1, value2, "accountDeleted");
            return (Criteria) this;
        }

        public Criteria andAccountDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("account_deleted not between", value1, value2, "accountDeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated do_not_delete_during_merge Sat Jan 08 14:40:09 PST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Sat Jan 08 14:40:09 PST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}