package com.bruincreates.server.dao.po;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobile
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    private Integer mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.profile_name
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    private String profileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.avatar_url
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.bio
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    private String bio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.data_created
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    private Date dataCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.role
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    private Integer role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.verified
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    private Integer verified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.locked
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    private Integer locked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.disabled
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    private Integer disabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.deleted
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobile
     *
     * @return the value of user.mobile
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public Integer getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobile
     *
     * @param mobile the value for user.mobile
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public void setMobile(Integer mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.profile_name
     *
     * @return the value of user.profile_name
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public String getProfileName() {
        return profileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.profile_name
     *
     * @param profileName the value for user.profile_name
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public void setProfileName(String profileName) {
        this.profileName = profileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.avatar_url
     *
     * @return the value of user.avatar_url
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.avatar_url
     *
     * @param avatarUrl the value for user.avatar_url
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.bio
     *
     * @return the value of user.bio
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public String getBio() {
        return bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.bio
     *
     * @param bio the value for user.bio
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public void setBio(String bio) {
        this.bio = bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.data_created
     *
     * @return the value of user.data_created
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public Date getDataCreated() {
        return dataCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.data_created
     *
     * @param dataCreated the value for user.data_created
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public void setDataCreated(Date dataCreated) {
        this.dataCreated = dataCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.role
     *
     * @return the value of user.role
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.role
     *
     * @param role the value for user.role
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.verified
     *
     * @return the value of user.verified
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public Integer getVerified() {
        return verified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.verified
     *
     * @param verified the value for user.verified
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public void setVerified(Integer verified) {
        this.verified = verified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.locked
     *
     * @return the value of user.locked
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public Integer getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.locked
     *
     * @param locked the value for user.locked
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public void setLocked(Integer locked) {
        this.locked = locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.disabled
     *
     * @return the value of user.disabled
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public Integer getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.disabled
     *
     * @param disabled the value for user.disabled
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public void setDisabled(Integer disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.deleted
     *
     * @return the value of user.deleted
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.deleted
     *
     * @param deleted the value for user.deleted
     *
     * @mbg.generated Tue Jan 11 14:37:11 PST 2022
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}